sudo: false
language: ruby
rvm:
  - ruby-head
  - 2.3.0
  - 2.1.0
  - jruby-head
  - jruby-9.0.5.0
matrix:
  allow_failures:
  - rvm: ruby-head
  - rvm: jruby-head

before_install: gem install bundler -v 1.13.0
